image: jazzypro/ubuntu-frontend:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ansible-playbook ansible/build.yml -v
  artifacts:
    paths:
      - dist/
  only:
    - /^dev-.*$/
    - master

deploy-dev:
  stage: deploy
  script:
    - ansible-playbook ansible/deploy.yml -v
  dependencies:
    - build
  only:
    - master
    - /^dev-.*$/
  environment:
    name: dev/$CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_NAME.metasfresh.ci.jzapp.io/
