name: test
on:
  workflow_run:
    workflows: [cicd]
    types:
      - completed

jobs:

  init:   
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.sanitize.outputs.refname }}-${{ github.event.workflow_run.run_number }}.${{ github.event.workflow_run.run_attempt }}
    env:
      MF_REF_NAME: ${{ github.event.workflow_run.head_branch }}
    steps:
      - name: print-vars
        run: env
      - name: print-github-context
        run: echo '${{ toJSON(github) }}'
      - name: sanitize-ref-name
        id: sanitize
        run: 'echo "::set-output name=refname::$(echo $MF_REF_NAME | sed -r ''s/([^a-zA-Z0-9.]+)/-/g'' | sed -r ''s/(^-|-$)//g'')"'
      - name: print-sanitizef-ref-name
        run: echo ${{ steps.sanitize.outputs.refname }}

  cucumber:
    runs-on: ubuntu-latest
    needs: [init]
    environment: 'test'
    continue-on-error: true
    steps:
      - name: run-cucumber-tests
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
          refname: ${{ needs.init.outputs.tag }}
        timeout-minutes: 60
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e "refname=$refname" mazorn/metas-cucumber:$refname-run 

  cypress:
    if: ${{ false }}  # disable for now
    runs-on: ubuntu-latest
    needs: [init]
    environment: 'test'
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: build-e2e
        run: |
          docker buildx build \
          -f docker-builds/Dockerfile.e2e \
          --build-arg REFNAME=${{ needs.init.outputs.tag }} \
          -t metas-e2e:latest \
          .
      - name: run-cypress-tests
        env:
          mysecret: ${{ secrets.TESTMO_TOKEN }}
          refname: ${{ needs.init.outputs.tag }}
        timeout-minutes: 120
        run: |
          cd docker-builds/e2e
          echo "$mysecret" > mysecret
          docker-compose up --abort-on-container-exit --exit-code-from e2e
          docker-compose down