# docker-compose.yml file

services:

  db:
    image: $mfregistry/metas-db:$mfversion
    ports:
      - "15432:5432"
    environment:
      # run the database on the initial data
      # so we can later commit it again to create the preloaded db with migrations applied
      # /data directories can't be persisted with docker commit!
      - PGDATA=/var/lib/postgresql/initdata
    healthcheck:
      test: pg_isready -h localhost -U metasfresh -d metasfresh -t 1
      interval: 10s
      timeout: 10s
      start_period: 60s
      retries: 30
    deploy:
      mode: replicated
      replicas: 1

  migration:
    image: $mfregistry/metas-db-migration-tool:$mfversion
    environment:
      - "JAVA_OPTS=-i -v"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1


